### ISSUE TITLE
checkin progress doesnt end. cant do new checkin unless restart

### ISSUE THREAD

**Issue by halmsx** [opensourceBIM/BIMserver#975] opened 2019-05-02 11:13 UTC
hi

have a little problem here with checkin

sometimes when doing simultaneous checkin, the progress will get stuck indefinitely. and i wont be able to do new checkin unless i restarted the bimserver.

is there a way to clear this using the api? cant find anything in ServiceInterface.

thank in advance.

**Comment by rubendel** [comment] 2019-05-10 06:13
Duplicate of https://github.com/opensourceBIM/BIMserver/issues/978

**Closed by rubendel** 2019-05-10 06:13 UTC
