### ISSUE TITLE
Model visualization error on Apple Silicon

### ISSUE THREAD

**Issue by GiacomoManzoli** [opensourceBIM/BIMserver#1301] opened 2023-07-07 09:59 UTC
**Describe the bug**
When computer running the bimvie.ws web application has an Apple Silicon processor (es: M2), the 3D model is displayed without colors.

**To Reproduce**
Open a project on any mac device with an Intel processor and the model is displayed correctly.
Open the same project in a mac device with an ARM/Silicon processor and the model is displayed without colors.

**Expected behavior**
The two model should be displayed in the same way.

**Screenshots**
Mac Intel
<img width="1539" alt="Mac Intel" src="https://github.com/opensourceBIM/BIMserver/assets/6218623/dd53b076-145e-422e-812e-0353b02897ea">
Mac Silicon
<img width="1381" alt="Mac Silicon M1" src="https://github.com/opensourceBIM/BIMserver/assets/6218623/f4e667ba-578b-49ac-8f73-5802b034687a">

**Additional context**
- It seems to be a "client side problem", in my case the server is the same and it's running on a Mac Intel.
- As far as devices goes, i've noticed that with macOS Ventura (latest public release), the processor M1 works fine, while the successors (M1 Pro/Max/Ultra and M2 series) has the issues. With the newer macOS Sonoma (still in beta) also the M1 processor has the issue.

**Comment by hlg** [comment] 2023-07-09 11:13
Appears to be duplicate of #1250.

**Comment by GiacomoManzoli** [comment] 2023-07-10 10:58
Yes, the behavior it's the same. I've tried different browser but nothing. 
It has been more than one year since #1250, do you guy have any idea? Unfortunately, these Apple Silicon processors are becoming a lot more popular

**Comment by zaqifathis** [comment] 2024-11-21 15:10
I will close this issue to simplify the discussion and will provide any updates in #1250

**Closed by zaqifathis** 2024-11-21 15:10 UTC
