### ISSUE TITLE
"ClassCastException" "org.bimserver.models.ifc2x3tc1.Tristate cannot be cast to java.lang.Boolean"

### ISSUE THREAD

**Issue by motjokk** [opensourceBIM/BIMserver#1027] opened 2019-08-13 13:01 UTC
Issue on Bimserver v. 1.5.~~62~~ 162 request using JSON.

getting requestType: "BOOLEAN" of "Pset_SpaceCommon" Property: "HandicapAccessible"
Bimserver threw "ClassCastException" "org.bimserver.models.ifc2x3tc1.Tristate cannot be cast to java.lang.Boolean"

This seems to be the same issue as #971

**Comment by rubendel** [comment] 2019-08-13 15:01
You mention another issue which indeed looks like the same problem. In that issue the problem is reported to be fixed. The BIMserver version mentioned in that issue is 1.5.125 and you are using 1.5.62, don't you think it's only logical that it's not fixed in 1.5.62?

**Comment by motjokk** [comment] 2019-08-13 16:41
oh, I see the mistake. I mean 1.5.162.

**Comment by rubendel** [comment] 2019-11-08 15:11
This could still be a bug, but more info is needed, which API method are you calling?

**Comment by motjokk** [comment] 2019-11-09 10:59
Hi,

I am calling the `getBooleanAttribute` method, from `LowLevelInterface`.

**Closed** 2024-11-29 12:25 UTC
Labels: bug, low level interface, good first issue
