### ISSUE TITLE
Mac m1 jar file error

### ISSUE THREAD

**Issue by kwangheum** [opensourceBIM/BIMserver#1216] opened 2021-10-06 08:55 UTC
![스크린샷 2021-10-06 오후 5 54 12](https://user-images.githubusercontent.com/6241343/136171668-1487b7cf-c6fa-42e8-ad0a-899a31ffbcc2.png)

check pleas...

**Comment by hlg** [comment] 2021-10-06 16:08
For the future: Please do not create screenshots of log files etcetera, copy and paste the actual text.
Also check the issue list before opening a new issue. This is a duplicate of #1118 and will be closed.

**Closed by hlg** 2021-10-06 16:08 UTC
