### ISSUE TITLE
Error when installing plugins Heap Space

### ISSUE THREAD

**Issue by alabrazi** [opensourceBIM/BIMserver#658] opened 2017-11-14 16:02 UTC
Hi,
I am getting the following error when installing BIMserver 1.5.90 plugins on MacOS High Sierra which has to do with heap size. Is this error caused because my computer ,with 2GB RAM,  does not have enough memory ?
```

17:57:16.168 [PluginInterface.getPluginBundle] DEBUG org.apache.http.wire -  << "[0xb4]?[0xbe]m[0xbb][0xeb][0x1e]}[0x90]H[0xc7][0x8b][0xbf][0xe3]'y+[0xfc][0xc9][0xde]'[0xba][0xcf]W[0xa5][0xae][0xd3]w[0x1a]\[0x9a][0xc2][[\r][0x9a]R[0xab]}[0xe8][0xfd][0x17][0xa4][0xa0][0xff]/K[0xcd][0x91][0xf4]`^[0x9a]*2[0xfb].[0xde][0x11]z\[0xba][0xb7])[0xc4]oZ0e[0xc4][0xf1][0xdb]b[0xd5][0xb7][0x85][0xd2]u9[0xec]^2/[0x81][0xa3]FF[0x1c]pLO[0xe0][0x98][0xd6]&[0xc7][0xc][0x99]I[0xcd][0[0xce][0xd1]VI[0xcd]>[0xcb][0xa4]4[0xec]?[0xe0][0xae][0x8b][0xd1][0x92][0xfe][0xf4][0x1b][0xbc][0xc4][0xb3][0xe3]tp[0x1e][0x0][0xb9][0xe5][^[0xb5][0xb6][0xe9][0x3]r[0xb3][0xcf]<[0xb8][0xff][0x96][0xe7][0x5][0xec][0x97]|f`|by[0xcc][0xbe][0xda][0xe2][0xe9][0xd4]yG[0xfa][0xbc][0xc2])'[0xdf][0xeb][0xc4][0x2]x[0xf9][0xb5]-^[0xca][0xb9][0x9][0xa5][0x84]{[0x93][0x8b][0x95][0xd2][0xf0]w*[0xc9][0x8f][0xa5][0x9c][0xbb][0x85]J[0xd9]Z[0xa2][0x94][0xc0][0xException in thread "Sysin reader" java.lang.OutOfMemoryError: Java heap space
	at javax.swing.text.GapContent.allocateArray(GapContent.java:94)
	at javax.swing.text.GapVector.resize(GapVector.java:214)
	at javax.swing.text.GapVector.shiftEnd(GapVector.java:229)
	at javax.swing.text.GapContent.shiftEnd(GapContent.java:345)
	at javax.swing.text.GapVector.open(GapVector.java:201)
	at javax.swing.text.GapVector.replace(GapVector.java:142)
	at javax.swing.text.GapContent.insertString(GapContent.java:132)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:723)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.JTextArea.append(JTextArea.java:477)
	at org.bimserver.starter.Starter$1.write(Starter.java:116)
	at java.io.PrintStream.write(PrintStream.java:480)
```

**Comment by rubendel** [comment] 2017-11-17 19:07
There seems to be a problem with logging, it's logging way too much, which is causing the error. I have had more reports about this, but have not figured out the cause yet. Are you starting with a new home directory or using an existing one?

**Comment by rubendel** [comment] 2017-11-20 14:27
This should be fixed now in https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.92

**Closed by rubendel** 2017-11-20 14:27 UTC
