### ISSUE TITLE
IFC4X3 ADD2.ecore

### ISSUE THREAD

**Issue by myfulltexts** [opensourceBIM/BIMserver#1318] opened 2024-05-17 00:35 UTC
hello everyone
     how can i get a IFC4X3 ADD2.ecore ？ anywhere can download it?

**Comment by hlg** [comment] 2024-05-17 08:28
Duplicate of #1236. The question is discussed there: the ecore file for a schema is to be generated from the respective exp file.

**Closed as not planned by hlg** 2024-05-17 08:27 UTC
