### ISSUE TITLE
changing port number using JAR breaks 

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMserver#917] opened 2019-01-30 20:26 UTC
**Describe the bug**
changing the port of the jar starter doesn't seem to change the urls in some of the apps

**To Reproduce**
1. start bimserver jar with port 8082
2. everything works
3. stop server
4. change port number in jar starter  to 8080
5. start server again
6. go to localhost:8080/apps/bimviews
7. check the console.

I'm getting the error: 
cannot connect to http://localhost:8082/json 

Seems the server connects to the  'old' 8082 port

**Comment by rubendel** [comment] 2019-01-30 20:34
A server does not connect, it binds. And it _does_ bind on the new port. But, since the SiteAddress setting has not changed, the UI still connects to the old url.

We could fix this by having the JAR starter connect to the server via the API and change the SiteAddress, but the problem is that the JAR starter does not know the credentials of the server where it needs admin rights.

I guess this is yet another good reason to try and get rid of the SiteAddress setting altogether.

**Comment by rubendel** [comment] 2019-01-31 21:16
This is now fixed in 1.5.124. BIMvie.ws is now not using the SiteAddress anymore and simply infers the BIMserver API endpoint URL from the URL in the browser. We can do this because nobody is running BIMvie.ws on a non-BIMserver webserver.

**Closed by rubendel** 2019-01-31 21:16 UTC
