### ISSUE TITLE
can't restart the BIMserver.jar

### ISSUE THREAD

**Issue by hualunchang** [opensourceBIM/BIMserver#580] opened 2017-06-30 02:59 UTC
when I first deployed the BIMserver.jar in my computer , it can work properly. But when I shut down the BIMserver and restart the BIMserver .jar, it seem couldn't start. the console print the log like this:

org.bimserver.BimserverDatabaseException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1127)
	at org.bimserver.BimServer.start(BimServer.java:717)
	at org.bimserver.JarBimServer.start(JarBimServer.java:85)
	at org.bimserver.JarBimServer.main(JarBimServer.java:53)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.bimserver.plugins.PluginManager.loadFromPluginDir(PluginManager.java:1362)
	at org.bimserver.BimServer.initDatabaseDependantItems(BimServer.java:1123)
	... 3 common frames omitted

please tell me how to solve this problem, thanks

**Comment by rubendel** [comment] 2017-07-07 06:59
Have you perhaps also updated to a different version of BIMserver?

**Comment by Nacho-Domenech** [comment] 2017-07-12 22:24
I have exactly the same problem with bimserverjar-1.5.76.jar. Any help?
No updated to a different version of BIMserver. I opened all local ports, change port to 8081 in Bimserver, clear cache of webbrowsers (Chrome, Firefox and Safari)....

**Comment by hlg** [comment] 2017-09-21 03:51
This seems to be a duplicate of #565. I got an error with this same stacktrace after installing a plugin and then restarting BIMserver. BIMserver retrieves the repository location to resolve dependencies from the POM in the plugin. If there is non it fails. Thus it can be fixed by adding the following lines to the `pom.xml` inside the plugin jar:

    <repositories>
      <repository>
        <id>central</id>
        <url>http://repo1.maven.org/maven2</url>
      </repository>
    </repositories>

I am not sure whether it is a good idea to let the plugin decide about the dependency resolution location. You may want to resolve all dependencies from a custom repository. Also there is an option to configure the plugin repository location in the server settings, so why not use this?

**Comment by rubendel** [comment] 2018-09-26 07:47
I think this was fixed

**Closed by rubendel** 2018-09-26 07:47 UTC
