### ISSUE TITLE
can not install plugins offline in bimserver 1.5.162 and 1.5.182 

### ISSUE THREAD

**Issue by chaogis** [opensourceBIM/BIMserver#1148] opened 2020-07-12 13:11 UTC
Hello, i am from china,  i can't install any plugin online because i do not have a working outgoing internet connection.
I use apache-tomcat-9.0.36 and jdk1.8.0_144 on windows 10.
I can not install essential piugins successlly by upload downloaded plugin jar file. The following is my problem.

First, on bimserver 1.5.162, for ifcplugins and  ifcopenshellplugin, I downloaded( from http://repo.jenkins-ci.org/public/org/opensourcebim/) and tried to install almost every version, but didn't install successfully.

Then, on bimserver 1.5.182, i download the following plugins:

**bimserverapi-0.0.176.jar
bimsurfer3-0.0.272.jar
bimviews-0.0.184.jar
binaryserializers-0.0.93.jar
ifcopenshellplugin-0.5.91.jar
ifcplugins-0.0.99.jar**

but none of them can install successfully.

I wonder if i had not find the correct version? Can you please point out the correct version for every plugin when a  new version bimserver release .

Expect you reply soon, thank you.

**Comment by hlg** [comment] 2020-07-12 17:05
There is no way to find the matching plugins for a particular BIMserver version, but you can verify from the plugin side which BIMserver version they where released with. Just look in the POM file's dependency section and check the version of the org.opensourcebim#pluginbase or org.opensourcebim#shared dependency. For instance, the [0.0.99 tag for IfcPlugins](https://github.com/opensourceBIM/IfcPlugins/commits/ifcplugins-0.0.99) has BIMserver 1.5.182 in its dependencies. You can also find the POMs on Maven.

Some plugins require an internet connection beyond installation, for instance the IfcOpenShell plugin will download the latest binaries depending on your OS.

**Comment by chaogis** [comment] 2020-07-14 01:50
> There is no way to find the matching plugins for a particular BIMserver version, but you can verify from the plugin side which BIMserver version they where released with. Just look in the POM file's dependency section and check the version of the org.opensourcebim#pluginbase or org.opensourcebim#shared dependency. For instance, the [0.0.99 tag for IfcPlugins](https://github.com/opensourceBIM/IfcPlugins/commits/ifcplugins-0.0.99) has BIMserver 1.5.182 in its dependencies. You can also find the POMs on Maven.
> 
> Some plugins require an internet connection beyond installation, for instance the IfcOpenShell plugin will download the latest binaries depending on your OS.

Thanks for your reply. Now i can find the suitable plugin for specified BIMServer.  However, when i download the plugin from http://repo.jenkins-ci.org/public/org/opensourcebim/ and install offline for bimserver 1.5.181, none of them can install successfully. Can you tell me what's the problem? I expect your reply, thank you.

**Comment by hlg** [comment] 2020-07-14 06:16
The cause is hard to tell without any details about the error you are facing. I just verified with the latest snapshot and don't see any issues installing offline plugins. Try the latest release and the following initial plugins: bimviews, console, and ifcplugins. As mentioned earlier, some plugins won't install without internet connection. Another option (maybe your best bet) is to set up BIMserver with an internet connection available, including plugin installation. Then you can copy and use that "installation" (home directory without any IFC data in database) in an offline context.

**Comment by chaogis** [comment] 2020-07-14 08:56
> The cause is hard to tell without any details about the error you are facing. I just verified with the latest snapshot and don't see any issues installing offline plugins. Try the latest release and the following initial plugins: bimviews, console, and ifcplugins. As mentioned earlier, some plugins won't install without internet connection. Another option (maybe your best bet) is to set up BIMserver with an internet connection available, including plugin installation. Then you can copy and use that "installation" (home directory without any IFC data in database) in an offline context.

OK，today i have installed all essential plugins for bimserver 1.5.182 online successfully. Thank you very much.

**Comment by acrimat** [comment] 2020-07-14 18:27
That's good chaogis. What did you change?
I'm still stuck at 
```
Installing plugins...
		All remote plugins successfully installed
		Installing uploaded plugin shared-1.5.182.jar
	-->	org.bimserver.shared.exceptions.UserException
```
while trying to install `bimserver 1.5.182` with these plugins (via offline jar-file):
```
bimviews 0.0.184
console 0.0.67
ifcplugins 0.0.99
pluginbase 1.5.182
shared 1.5.182
```
throwing this error (from bimserver.log):
```
2020-07-14 20:12:50,443 ERROR [PluginInterface.installPluginBundleFromFile] o.b.d.a.InstallPluginBundleFromBytes [InstallPluginBundleFromBytes.java:68]
java.lang.NullPointerException: null
        at org.bimserver.database.actions.InstallPluginBundleFromBytes.execute(InstallPluginBundleFromBytes.java:57)
        at org.bimserver.database.actions.InstallPluginBundleFromBytes.execute(InstallPluginBundleFromBytes.java:35)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
        at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundleFromFile(PluginServiceImpl.java:1434)
        at org.bimserver.generated.PluginInterfaceReflectorKVGTRbuZhnXK_1.callMethod(PluginInterfaceReflectorKVGTRbuZhnXK_1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
```

Any hint is appreciated.

**Comment by hlg** [comment] 2020-07-14 19:32
Why would you want to install "pluginbase" and "shared"? These are not plugins bundles - thus installation fails.

**Comment by acrimat** [comment] 2020-07-14 20:03
The answer is: because I don't know what I'm doing. I'm not an IT-guy at all, more between an architect and a draftsman. It's my first contact with Maven and JavaScript and Tomcat and JSON and all that good stuff... 
I want to get this up and running by all means, so I'm kind of bruteforcing it.

So now i guess I'm doing the same thing, but without including `pluginbase `and `shared`. Unfortunatelly I'm getting another error:
```
All remote plugins successfully installed
		Installing uploaded plugin ifcplugins-0.0.99.jar
		Failed to collect dependencies at org.opensourcebim:shared:jar:1.5.182
```
bimserver.log:
```
2020-07-14 21:45:32,509 ERROR [PluginInterface.installPluginBundleFromFile] o.b.d.a.InstallPluginBundleFromBytes [InstallPluginBundleFromBytes.java:68]
org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.opensourcebim:shared:jar:1.5.182
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
        at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:176)
        at org.bimserver.plugins.PluginBundleManager.install(PluginBundleManager.java:134)
        at org.bimserver.database.actions.InstallPluginBundleFromBytes.execute(InstallPluginBundleFromBytes.java:66)
        at org.bimserver.database.actions.InstallPluginBundleFromBytes.execute(InstallPluginBundleFromBytes.java:35)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
        at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundleFromFile(PluginServiceImpl.java:1434)
        at org.bimserver.generated.PluginInterfaceReflectorGeGTOUNVUkgv_1.callMethod(PluginInterfaceReflectorGeGTOUNVUkgv_1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
```

**Comment by hlg** [comment] 2020-07-14 20:25
I suggest to not do the setup and plugin installation offline. Find a possibility to do it online and afterwards you can work offline if you have to.

**Comment by chaogis** [comment] 2020-07-15 03:44
> The answer is: because I don't know what I'm doing. I'm not an IT-guy at all, more between an architect and a draftsman. It's my first contact with Maven and JavaScript and Tomcat and JSON and all that good stuff...
> I want to get this up and running by all means, so I'm kind of bruteforcing it.
> 
> So now i guess I'm doing the same thing, but without including `pluginbase `and `shared`. Unfortunatelly I'm getting another error:
> 
> ```
> All remote plugins successfully installed
> 		Installing uploaded plugin ifcplugins-0.0.99.jar
> 		Failed to collect dependencies at org.opensourcebim:shared:jar:1.5.182
> ```
> 
> bimserver.log:
> 
> ```
> 2020-07-14 21:45:32,509 ERROR [PluginInterface.installPluginBundleFromFile] o.b.d.a.InstallPluginBundleFromBytes [InstallPluginBundleFromBytes.java:68]
> org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.opensourcebim:shared:jar:1.5.182
>         at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
>         at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
>         at org.bimserver.plugins.PluginBundleManager.loadDependencies(PluginBundleManager.java:176)
>         at org.bimserver.plugins.PluginBundleManager.install(PluginBundleManager.java:134)
>         at org.bimserver.database.actions.InstallPluginBundleFromBytes.execute(InstallPluginBundleFromBytes.java:66)
>         at org.bimserver.database.actions.InstallPluginBundleFromBytes.execute(InstallPluginBundleFromBytes.java:35)
>         at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:775)
>         at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
>         at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundleFromFile(PluginServiceImpl.java:1434)
>         at org.bimserver.generated.PluginInterfaceReflectorGeGTOUNVUkgv_1.callMethod(PluginInterfaceReflectorGeGTOUNVUkgv_1.java)
>         at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
>         at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
>         at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
>         at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
>         at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> ```

I install plugins successfully online yestoday. I think it's difficult to install essential plugins successfully offline, it always throw some exception. As @hlg said, you can try online way.

**Comment by Mit-hf** [comment] 2020-09-28 02:59
![Uploading image.png…]()

**Comment by Mit-hf** [comment] 2020-09-28 03:01
![微信图片_20200928105951](https://user-images.githubusercontent.com/46521167/94386269-cc963a00-0179-11eb-8d5a-5676112709fa.png)
Use idea to open the source code, but the file here cannot be imported. Does anyone know why? Look forward to your reply!

**Comment by Mit-hf** [comment] 2020-09-28 03:01
![Uploading 微信图片_20200928105951.png…]()

**Comment by Mit-hf** [comment] 2020-09-28 03:02
Ifc2x3tc1Package and Ifc4Package

**Comment by hlg** [comment] 2020-09-28 17:54
@Mit-hf, your comments don't have anything to do with this issue. Next time, please open a new issue in such a case.

Intellij IDEA has a restriction to exclude large files from indexing. The files can be opened and edited, probably even debugged etc. They are just not indexed for navigating to these classes and finding usages. You can change the setting (idea.max.intellisense.filesize) to a higher value, but it may decrease performance.

**Comment by Mit-hf** [comment] 2020-09-29 00:47
well! Next time open a new page to ask questions. Thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opensourceBIM/BIMserver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 凌晨1:55
收件人:&nbsp;"opensourceBIM/BIMserver"<BIMserver@noreply.github.com&gt;;
抄送:&nbsp;"568530599"<568530599@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [opensourceBIM/BIMserver] can not install plugins offline in bimserver 1.5.162 and 1.5.182  (#1148)





 
@Mit-hf, your comments don't have anything to do with this issue. Next time, please open a new issue in such a case.
 
Intellij IDEA has a restriction to exclude large files from indexing. The files can be opened and edited, probably even debugged etc. They are just not indexed for navigating to these classes and finding usages. You can change the setting (idea.max.intellisense.filesize) to a higher value, but it may decrease performance.

**Closed** 2021-01-18 18:11 UTC
