### ISSUE TITLE
IFC Objects lost in translation

### ISSUE THREAD

**Issue by TitouanGisle** [opensourceBIM/BIMserver#1000] opened 2019-06-27 12:32 UTC
Hello !

I've uploaded an IFC4 file on my local BIMserver v1.5.147, but a few IfcWallStandardCases seem to be missing from it. They are not displayed in the viewer nor the object tree (I tried the BIMsurfer included in BIMvie.ws and BIMsurfer 3). Another viewer (BIMvision), on which I tried to view my model, displayed everything well.

The method _GetDataObjectFromGuid_, executed from Console, does return the objects and the same information as in the IFC file.

When I re-download the IFC file, the objects are still present, and the file displays fine in BIMvision, but trying to checking it in BIMserver returns  errors.

I thank you for your consideration.

**Comment by rubendel** [comment] 2019-06-27 15:10
Is there anything in the BIMserver log file during upload? Are there perhaps issues with generating the geometry?

Please post both the relevant part of the BIMserver log as well as the geometry generation report linked to the Revision as Extended Data.

If you can share the IFC file that would be even more useful, we can try to reproduce it (or a similar file with the same problem).

**Comment by TitouanGisle** [comment] 2019-06-27 15:38
Sure !

Here's the file :

[Conference Center - IFC4.zip](https://github.com/opensourceBIM/BIMserver/files/3335442/Conference.Center.-.IFC4.zip)


Here are the lines from the BIMserver log :

_2019-06-27 17:19:18,076 
INFO [pool-1-thread-30] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:604] writes: 5000000, 1811 ms sync

2019-06-27 17:22:34,337
INFO [pool-1-thread-30] o.b.g.StreamingGeometryGenerator [StreamingGeometryGenerator.java:623] Rendertime: 03m 07s, Reused (by hash): 2,36 MB, Reused (by transformation): 0 B, Reused (by mapping): 103,16 MB, Total: 173,36 MB, Final: 67,84 MB

2019-06-27 17:22:34,343
ERROR [pool-1-thread-30] o.b.g.StreamingGeometryGenerator [StreamingGeometryGenerator.java:625] Number of erroneous files: 99


And here is the geometry generation report :
[GeometryExtendedData.txt](https://github.com/opensourceBIM/BIMserver/files/3335495/GeometryExtendedData.txt)

**Comment by rubendel** [comment] 2019-06-28 08:41
So far, what I get here with roughly the same version:
- Some IfcDuctFitting and IfcPipeFitting objects result in errors (just as in your report)
- Strangely, the IfcWallStandardCase objects are all going OK here (no errors in the geometry generation report as opposed to your report). Also I think they are visible in BIMvie.ws/BIMsurfer, but it would be useful to know one of the GUIDs of the walls that do not show for you.

I am using the exact same version of IOS.

So what's interesting to know is on what OS you are (I have tested this on Window 10 so far).

**Comment by TitouanGisle** [comment] 2019-06-28 10:04
Curiouser and curiouser.

My server also runs on Windows 10, and the walls are displayed just fine on a server running on a Debian9 VM. Both were installed automatically from the .war by tomcat9. 

As for the GUIDs : 2N8Cd2RGP5i9wSaakjj2zY is the most consequent wall.

**Comment by rubendel** [comment] 2019-06-28 10:47
Ok I have a clue now. IOS has a few different settings. With both layersets and quantities enabled I can now reproduce your situation, with some walls (including 2N8Cd2RGP5i9wSaakjj2zY) missing.

There have been bugs in BIMserver where it does not correctly report and/or apply these settings, which makes it a bit harder to identify what's going on. This should be fixed in the next release.

I'll talk to the developer of IfcOpenShell and share the the model with him and report back in this issue.

**Comment by rubendel** [comment] 2019-06-28 11:15
After testing a bit more, it's the "Calculate Quantities" setting that causes some of the wall to not work. The other objects that always fail are interesting to investigate as well btw.

**Comment by TitouanGisle** [comment] 2019-06-28 12:17
All right, thanks a bunch !

**Comment by aurelien-gille** [comment] 2020-07-07 14:08
Hi,
I think i run onto the same error. Is the problem solved for you ? If yes how did you manage it ?
Thanks

**Comment by hlg** [comment] 2021-03-01 18:46
The original file is invalid IFC according to the current IFC4 specification, see also issue #1084. In an attempt to reproduce the issues I have extracted a few pipes and the ducts and these still fail with the latest IfcOpenShell engine.

For the wall I cannot reproduce the issue (`GUID 2N8Cd2RGP5i9wSaakjj2zY`, `#1143827`). I have extracted it with two walls that are connected to it, and with the respective material layer assignments. Maybe the wall issue has been resolved in IfcOpenShell in the meantime.

[confcenter_ducts.ifc.txt](https://github.com/opensourceBIM/BIMserver/files/6063771/confcenter_ducts.ifc.txt)
[confcenter_pipes.ifc.txt](https://github.com/opensourceBIM/BIMserver/files/6063772/confcenter_pipes.ifc.txt)
[confcenter_walls-connected-material.ifc.txt](https://github.com/opensourceBIM/BIMserver/files/6063773/confcenter_walls-connected-material.ifc.txt)

**Comment by hlg** [comment] 2021-03-01 19:23
The ducts and pipes issue seems to be solved in IfcOpenShell, likely with this issue: with https://github.com/IfcOpenShell/IfcOpenShell/issues/1269. In BIMserver, this can be verified with setting the commit sha to "517b819" in IfcOpenShell plugin settings.

**Comment by zaqifathis** [comment] 2024-10-25 12:29
the issue with missing object in model seems similar to this issue #1100 and here is the [details](https://github.com/opensourceBIM/BIMserver/issues/1100#issuecomment-2304771745)

**Comment by hlg** [comment] 2024-10-25 12:52
@zaqifathis I cannot find any IfcCircleHollowProfileDef entities in this file and also no 0-depth extrusions, so this was likely a different issue. Any issue in IfcOpenShell, where it cannot generate the geometry, will look similar to the BIMserver.

**Comment by hlg** [comment] 2024-11-01 19:01
This is the conference center file from the Auckland Open IFC Model Repository. Same file as in #1084. After fixing the IFC export errors, and with using IfcOpenShell version v0.7.0-c7830e9, geometry generation works just fine without any errors.

**Closed by hlg** 2024-11-01 19:01 UTC
