### ISSUE TITLE
How to show the IFC2X3 file to the web？

### ISSUE THREAD

**Issue by victor-freedom** [opensourceBIM/BIMserver#1293] opened 2023-05-05 03:01 UTC
I have three issues；

First:
I used bimserver v1.5.184.
when I start server，it has an error like 'Required dependency org.opensourcebim:bimserverapi is installed, but it's version (0.0.9) does not comply to the required version (0.0.83)', I install the BIMServer JavaScript API plugin by version 0.0.176.How can i resolve this problem?

Second:
BIMsurfer-before2019-master,I use this project or https://github.com/AECgeeks/BIMsurfer2/ to get data from bimserver  and then use xeoViewer(bimserver.html can only use  the xeoViewer,because at the BimServerModelLoader.loadFullModel-> loadOids call a method : viewer.taskStarted(),only xeoViewer has the method) to show the data.But, in the BimServerGeometryLoader,i can only get the new serializer "org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializerPlugin"( the BinaryGeometryMessagingStreamingSerializerPlugin3 is not exist at the version 1.5.184) and call the method o.bimServerApi.call("ServiceInterface", "download") to download the data,after this,there is an error shows in the bimserver like 
"17:23:28 ERROR [pool-1-thread-22]:                                                                                  (BimServer.java:240) 
java.lang.NullPointerException: null
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeGeometryData(BinaryGeometryMessagingStreamingSerializer.java:974)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeData(BinaryGeometryMessagingStreamingSerializer.java:771)
	at org.bimserver.serializers.binarygeometry.BinaryGeometryMessagingStreamingSerializer.writeMessage(BinaryGeometryMessagingStreamingSerializer.java:275)
	at org.bimserver.servlets.Streamer$1.run(Streamer.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
"。
I think this is the reason i can‘t show the data on the web。 
if I choose the bimserver in viesion 1.5.88 ,there is no problem and can show the data successful。
So, how can I do to solve this problem?
I just want to use bimserver in version 1.5.184 to show the IFC2X3 file on the web.

Third:
If the project BIMsurfer-before2019-master could match the bimserver v1.5.184?If it is not ,which project I can use to load the IFC2X3 data from bimserver v1.5.184 and show the data to the web or which bimserver version I can use to load the IFC2X3 data from bimserver and show the data to the web

**Comment by hlg** [comment] 2023-05-07 08:28
Duplicate of https://github.com/opensourceBIM/BIMsurfer/issues/112.

**Closed by hlg** 2023-05-07 08:28 UTC
