### ISSUE TITLE
Unable to checkin conccurently

### ISSUE THREAD

**Issue by tchegito** [opensourceBIM/BIMserver#927] opened 2019-02-08 10:38 UTC
**Describe the bug**
When 2 users are doing a check-in in 2 different sub-projects of a same project, one of them is well received, but the other fails.

**To Reproduce**
Have a project with two empty sub-projects.
Open 2 tabs in your browser pointing to each of the sub-project.
Do a checkin in both of them (I tried with different files, but not sure it's relevant)

**Expected behavior**
Upload ok. Even if project isn't refreshed for the two uploads, it's okay, I think.

Actually, one of the upload gets the following error:
`Caused by: org.bimserver.plugins.deserializers.DeserializeException: Zip files must contain exactly one IFC-file, this zip-file looks empty`

That's weird, because in the folder incoming/<userName> we can see that files are well uploaded.

**Comment by tchegito** [comment] 2019-02-08 10:43
I've seen that bulkupload works well to nearly achieve this task, at least concurrent uploads from the same person. But my original use case is when 2 users are pushing their work at the same time. So bulk isn't appropriate in this context.

**Comment by rubendel** [comment] 2019-02-11 08:47
I could not reproduce this, can you elaborate on the used IFC files. Are both zipped models? Are the names different?

**Comment by tchegito** [comment] 2019-02-11 09:30
Actually, I tried with IFCZIP files (with different names), from BIMCollab here: https://www.bimcollab.com/en/Support/Support/Downloads/Examples-templates

(By the way, I made a pull request with one these files which leaded to a crash about an encoding problem : https://github.com/opensourceBIM/IfcPlugins/pull/15/commits/87602124d03708055bdbb0d12841a3b00f16cee7)

If I check in the files one after another, it's okay.

I will try with simple IFC file.

**Comment by rubendel** [comment] 2019-02-11 09:44
In the mean time I have been able to reproduce this, it does seem to be a problem that occurs when both:
- Zip files are used
- Concurrent modifications are happening, for example when checking-in files in 2 subprojects of the same main project at the same time (a lot of other scenarios will also incur concurrent modifications).

I'll post here when this is fixed. I have seen the other issue, will have a look at that later.

**Comment by tchegito** [comment] 2019-02-11 09:49
Thanks !

**Comment by rubendel** [comment] 2019-02-11 10:02
This is now fixed in https://github.com/opensourceBIM/BIMserver/commit/426ee3f80d0671b2e544dbd2692a0f389e12cb28

**Closed by rubendel** 2019-02-11 10:02 UTC

**Comment by tchegito** [comment] 2019-02-11 10:25
Great, it works well ! Thank you very much.
