### ISSUE TITLE
checkin on Linux failed, but works on OSX

### ISSUE THREAD

**Issue by rainerbreuss** [opensourceBIM/BIMserver#966] opened 2019-04-18 08:03 UTC
Hi Ruben, 
we have an IFC file that could not be checked in on Bimserver 125 running an o CentOS7 Server. The same file could be checked in without any problems on Bimserver 125 running on a MacBookPro.

On Centos7 the Server throws the follwowing Exception and restarts itself afterwards:

`2019-04-17 19:24:47,879 INFO [pool-9-thread-1] o.b.d.b.BerkeleyKeyValueStore [BerkeleyKeyValueStore.java:604] writes: 1000000, 2163 ms sync
2019-04-17 19:25:14,061 ERROR [GeometryRunner] o.b.g.StreamingGeometryGenerator [GeometryRunner.java:802] 
org.bimserver.plugins.renderengine.RenderEngineException: Exited with non-zero exit code: 137
	at org.ifcopenshell.IfcGeomServerClient.terminate(IfcGeomServerClient.java:730)
	at org.ifcopenshell.IfcGeomServerClient.close(IfcGeomServerClient.java:105)
	at org.ifcopenshell.IfcOpenShellEngine.close(IfcOpenShellEngine.java:83)
	at org.bimserver.renderengine.NoPoolingRenderEnginePool.returnObject(NoPoolingRenderEnginePool.java:40)
	at org.bimserver.geometry.GeometryRunner.run(GeometryRunner.java:777)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-17 19:26:29,261 INFO [bimserver.muiggbreuss.com-startStop-1] o.b.BimServer [BimServer.java:241] Starting BIMserver
`

The error happens in 'Generating Geometry' at about 50%. Client gets no message about the error, it shows the progress bar forever ...

The file is Ifc2x3, size is > 85MB. unfortunately we are not allowed to share the file.

Thanks.

**Comment by rubendel** [comment] 2019-04-18 13:06
BIMserver uses IfcOpenShell for generating the geometry. The non-zero exit code indicates that something went wrong in IfcOpenShell. Unfortunately the exit-code is also the only type of error reporting IfcOpenShell does (and the code itself also has no meaning).

So without the file there really isn't anything we can do to help. Since the file is working on OSX I would assume the problem to be something to do with library conflicts, it is running fine generally on Ubuntu Linux.

Oh one thing you could check is whether a simple/small IFC file works on your CensOS7 setup, so we at least know whether the problem is related to the file.

**Comment by rainerbreuss** [comment] 2019-04-18 13:19
we have other ifc files working without any problems on that CentOs7 server

**Comment by hlg** [comment] 2021-05-12 10:47
Is this still an issue?

**Comment by zaqifathis** [comment] 2024-10-25 11:07
Since we're focusing development on the latest version of BIMserver, we’ll close this issue for now. However, if it comes up in the current version, please feel free to reopen it.

**Closed by zaqifathis** 2024-10-25 11:07 UTC
Labels: bug

**Comment by hlg** [comment] 2024-10-25 12:53
I don't know about any code in the BIMserver where it restarts itself. Maybe an OS restart was triggered otherwise during the running check-in? This could have caused the IfcOpenShell instances to be killed and abort with that specific exit code and subsequently, after restart, the BIMserver came up again with the respective log message.
