### ISSUE TITLE
Many missing Property Sets

### ISSUE THREAD

**Issue by Chris-12** [opensourceBIM/BIMserver#1299] opened 2023-06-20 13:45 UTC
Hi,
In bimviews, and also in our javascript client, with a IF4 model, there are many missing Property Sets.

Even if we use query to perform the load of all of them with :
{
  "type": {
    "name": "IfcProduct",
    "includeAllSubTypes": true
  }}

As a comparison, in another program called BimVision (not a server but standalone) we get all of expected property sets :
Bim Vision -> OpenSource BIM Server:
Element Specific ->IfcBuildingElementProxy
Profile -> **missing** !
Constraints -> Constraints
Data -> **missing** !
Dimensions -> Dimensions
Electrical - Loads -> **missing** !
Identity Data -> **missing** !
Other -> Other
Phasing -> Phasing (but **missing** properties e.g. "4D_ID")

We are running last release: bimserverwar 184.
Is there a way to load all these missing property sets at client level (at preload time query, or else), or else ?
Regards,
Chris

**Comment by hlg** [comment] 2023-06-20 14:13
Can you share a (perhaps minimal) IFC sample with the properties that are missing such that we can reproduce it in BIMvie.ws? Also: where are the properties missing - when browsing in BIMvie.ws, when downloading via query, in the properties tab or somewhere else?

**Comment by Chris-12** [comment] 2023-06-26 08:22
Yes it can be viewed, but the model is private. I sent you a mail for you to download the model from our private storage.
The missing properties are in the property panel of BIMvie.ws via query and also after downloading the model with the API.

**Comment by hlg** [comment] 2023-06-28 04:47
Did you send the download link to bimserver@opensourcebim.org?

**Comment by Chris-12** [comment] 2023-06-28 07:55
Right, I did not use the correct address . Now I did.

**Comment by hlg** [comment] 2023-07-12 13:30
Thank you for the file. I don't see any properties missing. The following query retreives all property sets including their properties as well as the objects and type objects they are assigned to and in case of type objects also the related type instances. It should include the property sets you mentioned above.

~~~json
{ "type": "IfcPropertySet",
  "include": {
    "type": "IfcPropertySet",
    "fields": ["HasProperties", "DefinesOccurrence", "DefinesType"],
    "include": {
      "type": {"name": "IfcTypeObject", "includeAllSubTypes": true},
	  "field": "Types",
	  "include": {
	    "type": "IfcRelDefinesByType",
	    "field": "RelatedObjects"
      }
    }
  }
}
~~~

The above query works from the property set to the assigned object. But likewise you can go the other way round: For a given object or product you should be able to retrieve all assigned property sets (`IfcObject.IsDefinedBy`, `IfcRelDefinesByProperties.RelatingPropertyDefinition`). Note that some property sets are not assigned directly to the objects, but to their type objects. Thus you have to navigate to the type object (`IfcObject.IsTypedBy`, `IfcRelDefinesByType.RelatingType`) before retrieving the property sets using  an attribute chain similar to the one for `IfcObject`.

Property sets assigned to type objects may also be the reason that some properties do not appear very obviously in BIMvie.ws. Other applications may handle this differently, but in BIMvie.ws' property panel you see only direct properties of selected objects. However, you can easly modify this or access the type objects' property sets in your own application or client. In BIMvie.ws, you can also use the "Browse" tab to navigate all entities in a project and assure yourself that all the properties are actually there.

Hope that helps.

**Comment by Chris-12** [comment] 2023-09-11 09:29
Hi,
it works fine with information you gave. Thanks a lot.

**Closed** 2023-09-12 06:22 UTC
