### ISSUE TITLE
Error in Console getDownloadData

### ISSUE THREAD

**Issue by Claudiaa07** [opensourceBIM/BIMserver#427] opened 2016-11-14 09:19 UTC
Hi,

I want to have a compared file of 2 (revision) documents in my project. I have the roids and poid, serializeroid. I used the Guid based compare id in the getAllplugins for the mcid.

At the Console I use downloadCompareResults with all the above ids and type: modify and no sync.
I get a **number** as result and put it in getDownloadData.
Then i got an;
Error:  "__type": "ServerException",
      "message": "org.bimserver.models.store.impl.PluginDescriptorImpl cannot be cast to org.bimserver.models.store.ModelComparePluginConfiguration"

What do I have to do to get the file?

**Comment by rubendel** [comment] 2016-11-14 13:45
Not sure where the getAllplugins method can be found. Can you try getDefaultModelCompare? Also make sure that a working model compare engine is installed and selected as the default one under your user account.

**Comment by Claudiaa07** [comment] 2016-11-14 14:54
Oke I used the iod from getDefaultModelCompare (there is stated 'Named based' and in my user settings is at model compare engines: 
![image](https://cloud.githubusercontent.com/assets/22083595/20269074/fabebdba-aa81-11e6-9c39-7a08c7d2ea76.png)

But when I use compare in the console I got the error:

    "exception": {
      "__type": "UserException",
      "message": "java.lang.NullPointerException"
![image](https://cloud.githubusercontent.com/assets/22083595/20269164/5ce1ec2e-aa82-11e6-88bc-bc01304a33ba.png)

**Comment by rubendel** [comment] 2016-11-15 10:54
There were some regression bugs in the compare code causing this NPE, seems to be sort of fixed now, will be in the next release.

Just a heads-up. Compare has never really quite worked how most people expect it to work. It is a very crude implementation which is supposed to show how you can write a compare algorithm yourself in BIMserver.

**Closed** 2017-01-03 08:13 UTC
