### ISSUE TITLE
Empty mail when sending user reset password email

### ISSUE THREAD

**Issue by orashkenazi** [opensourceBIM/BIMserver#1072] opened 2019-12-16 14:56 UTC
Hello,

I am running bimserver  v1.5.162.

for some reason my bimserver sends empty messages to reset the password.

when i checked the log i understood it doesnt find the email template..

the emailtemplates folder in the home folder is empty, any idea why?

btw,
I skipped the setup step of the smtp server in the initial bimserver setup

thanks.

**Comment by rubendel** [comment] 2020-01-06 08:03
Not sure why it's empty, maybe this specific release did not copy them correctly. Have you tried a more recent release? Skipping the SMTP setup should have no effect on this. You could manually copy the templates, they have not changed in a while so you can pick any release you like.

Just checked 1.5.162, the templates are in the JAR file, so you can copy those. Also on my machine they do get copied, so it must be something specific for your platform.

**Comment by ts4iot** [comment] 2020-03-13 11:18
Hello,

i've the same problem with 1.5.182:
`2020-03-13 10:09:24,025 ERROR [org.bimserver.AuthInterface.requestPasswordChange] o.b.t.TemplateEngine [TemplateEngine.java:52]
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'password_reset_email_body.template'
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
        at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:343)
        at org.bimserver.templating.TemplateEngine.process(TemplateEngine.java:49)
        at org.bimserver.database.actions.RequestPasswordChangeDatabaseAction$1.execute(RequestPasswordChangeDatabaseAction.java:92)
        at org.bimserver.database.DatabaseSession.commit(DatabaseSession.java:259)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:777)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:767)
        at org.bimserver.webservices.impl.AuthServiceImpl.requestPasswordChange(AuthServiceImpl.java:112)
        at org.bimserver.generated.AuthInterfaceReflectordrFlYUKKTMXI_1.callMethod(AuthInterfaceReflectordrFlYUKKTMXI_1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:222)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:66)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by ts4iot** [comment] 2020-03-14 09:45
Hello,

now it works. I have to copy the emailtemplates from tomcat directory:

/usr/local/tomcat/webapps/ROOT/WEB-INF/emailtemplates

to 

/var/bimserver/home/emailtemplates

**Comment by hlg** [comment] 2022-07-21 14:59
I can reproduce this. Actually, the templates should be copied on home directory initialization, but they are not. Maybe there is something wrong with the WarResourceFetcher?

**Comment by hlg** [comment] 2022-08-03 16:15
It is WarResourceFetcher indeed. It keeps a list of paths: First is the BIMserver home directory, second the expanded war path. Now when the home directory is initiated, some directories and content are copied over into the home folder. When it comes to email templates, first an empty template directory is created, then template files to be copied are listed using the WarResourceFetcher. Resource fetcher goes through its list of paths and tries to find the directory. Now, since the home folder comes first, the resource fetcher finds the template directory just created and does not proceed to try the expanded war directory. The directory is empty and thus the list of template files to be copied is empty as well. That's how the empty template directory gets into existence. This will be fixed in next commit. Just have to check whether the home folder path is needed for something else by WarResourceFetcher.

**Closed** 2022-08-09 16:09 UTC
