### ISSUE TITLE
why plugin bimviews-0.0.184.jar install error?

### ISSUE THREAD

**Issue by lantianning** [opensourceBIM/BIMserver#1241] opened 2022-02-06 02:03 UTC
Setting up...
	Setting up admin account...
		Admin account successfully setup
	Skipping email setup...
	Checking internet connection _from_ your BIMserver...
		Your BIMserver does not seem to have a [working outgoing internet connection](https://github.com/opensourceBIM/BIMserver/wiki/Outgoing-internet-connection).
	Not installing extended data schemas because there is no internet connection
	Not installing plugins because there is no internet connection
		**Installing uploaded plugin bimviews-0.0.184.jar
		Required dependency org.eclipse.platform:org.eclipse.core.expressions is not installed**
	
	Setup successful, [refresh to go to the status page](http://localhost:8080/)

**Comment by hlg** [comment] 2022-02-06 08:15
Closing, because not enough information provided. Likely duplicate of #1189, solved in 9b381821e963eb9b3679c0b26f2b11a145822600 and ec4505d9d4cede9f033d9bc08c8ee95a3db22d24.

**Closed by hlg** 2022-02-06 08:15 UTC
