### ISSUE TITLE
 How can I add ifc4x3 version

### ISSUE THREAD

**Issue by PavelWhiteTiger** [opensourceBIM/BIMserver#1306] opened 2023-10-19 11:48 UTC
I'm try to add the ifc4x3 version.
Can you write how to do this?
I was able to generate ecore. What to do next?
How can i add ifc4x3 in file "models.genmodel"

**Comment by hlg** [comment] 2023-10-19 21:54
To update the genmodel you need to use Eclipse or write code for an external project if you want to do it programmatically. The required libraries have been removed from this (the main BIMserver) project to separate generator and runtime dependencies in commit 9433046. Before the removal, there was a class [DataObjectGenerator.java](https://github.com/opensourceBIM/BIMserver/blob/92ecc3af58dad16a3920f6ee8255f73759907f00/BimServer/src/org/bimserver/tools/generators/DataObjectGenerator.java) which looks like creating genmodel, but I doubt this class was maintained and correctly functioning.

Unfortunately I did not find the time to review and reproduce the schema update process and cannot come up with instructions just like that. Yet, i am happy to assist with trying to get this done and documented. I close this issue as duplicate of #1236 and ask to continue this thread there.

**Comment by hlg** [comment] 2023-10-19 21:54
duplicate of https://github.com/opensourceBIM/BIMserver/issues/1236

**Comment by hlg** [comment] 2023-10-19 21:55
duplicate of https://github.com/opensourceBIM/BIMserver/issues/1236

**Closed by hlg** 2023-10-19 21:55 UTC
